centos_build:
  stage: build
  tags:
    - centos
  script:
    - mkdir build
    - cd build
    - cmake .. 
    - cat tests/build_machine.hpp
    - make VERBOSE=1

centos_test:
  stage: test
  tags:
    - centos
  script:
    - mkdir build
    - cd build
    - cmake .. 
    - cat tests/build_machine.hpp
    - make VERBOSE=1
    - ctest -V

mac_build:
  stage: build
  tags:
    - mac
  script:
    - mkdir build
    - cd build
    - cmake .. 
    - cat tests/build_machine.hpp
    - make VERBOSE=1

mac_test:
  stage: test
  tags:
    - mac
  script:
    - mkdir build
    - cd build
    - cmake .. 
    - cat tests/build_machine.hpp
    - make VERBOSE=1
    - ctest -V

ubuntu_build:
  stage: build
  tags:
    - ubuntu
  script:
    - mkdir build
    - cd build
    - cmake .. 
    - cat tests/build_machine.hpp
    - make VERBOSE=1

win_build:
  stage: build
  tags:
    - windows
  script:
    - mkdir build
    - cd build
    - cmake ..
    - type tests\build_machine.hpp
    - cmake --build .

win_test:
  stage: test
  tags:
    - windows
  script:
    - mkdir build
    - cd build
    - cmake ..
    - type tests\build_machine.hpp
    - cmake --build . --config Release
    - ctest -V -C Release

