# C++ project
language: cpp
dist: trusty
rvm:
  - 2.3

matrix:
  include:
    # works on Precise and Trusty
    # - os: linux
    #   addons:
    #     apt:
    #       sources:
    #         - ubuntu-toolchain-r-test
    #       packages:
    #         - g++-4.9
    #   env:
    #      - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    - os: osx
      osx_image: xcode9
      env:
        - MATRIX_EVAL="CC=gcc && CXX=g++"

    - os: osx
      osx_image: xcode9.3
      env:
        - MATRIX_EVAL="brew install gcc; brew link --overwrite gcc && CC=gcc-7 && CXX=g++-7"

    - os: osx
      osx_image: xcode9
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang"

before_install:
    - eval "${MATRIX_EVAL}"

script:
  - mkdir -p build && cd build
  - cmake ..
  - make VERBOSE=1
  - ctest -V -j
  - cd ..